name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Checkout spry repo
        uses: actions/checkout@v5
        with:
          repository: programmablemd/spry
          token: ${{ secrets.GH_TOKEN }}
          path: spry

      - name: Copy lib/universal and lib/spawn to jsr_package/universal
        run: |
          cp -r spry/lib/universal/* jsr_package/universal/
          cp -r spry/lib/spawn/* jsr_package/universal/

      - name: Publish JSR package
        run: |
          cd jsr_package/universal
          npx jsr publish --allow-dirty
